######## @required: ENV_CI_TARGET_DOCKER_IMAGE ########
######## @required: ENV_CI_HOST_SHARE_PATH ########
name: x_docker_image_snapshot

x-host_share_path: &host_share_path "${ENV_CI_HOST_SHARE_PATH:-./x-host-shares}"
x-container_share_path: &container_share_path "/x-src/dist"

configs:
  pull_to_snapshot_entry_sh:
    content: |
      #!/bin/sh
      set -x
      for docker_image in $${ENV_CI_TARGET_DOCKER_IMAGE}
      do
        export ENV_CONTAINER_IMAGE_SAVENAME="dockerimg_$$(echo "$${docker_image}" | sed -e 's/\//~/g' -e 's/:/@/g')_$$(date +'%Y-%m-%dT%H-%M-%S%z')"
        docker pull "$${docker_image}"
        docker save "$${docker_image}" | gzip > "$${ENV_CONTAINER_SHARE_PATH}/$${ENV_CONTAINER_IMAGE_SAVENAME}.tar.gz"
      done
      ls -la "$${ENV_CONTAINER_SHARE_PATH}"

services:
  pull_to_snapshot:
    image: docker:latest
    working_dir: "/x-src"
    entrypoint: "./entry.sh"
    environment:
      ENV_CI_TARGET_DOCKER_IMAGE: "${ENV_CI_TARGET_DOCKER_IMAGE}"
      ENV_CONTAINER_SHARE_PATH: *container_share_path
    configs:
      - source: pull_to_snapshot_entry_sh
        target: "/x-src/entry.sh"
        mode: 0777
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: *host_share_path
        target: *container_share_path
        read_only: false
