name: x_pyt_store_llm_pip

x-user: &user "${ENV_CI_UID}:${ENV_CI_GID}"
x-host_share_path: &host_share_path "${ENV_CI_ARTIFACT_PATH}"
x-python_llm_store_pip_sh: &python_llm_store_pip_sh |
  set -x
  rm -rf ./dist/*
  cat > ./dist/llm_requirements.txt << EOF
  datasets==3.0.0
  transformers==4.44.2
  EOF
  pip download -r ./dist/llm_requirements.txt -d ./dist/pkgs

configs:
  python_llm_requirements_txt:
    content: |
      # pip dependencies tested in python:3.10.12
      torch==2.4.1
      # llm
      datasets==3.0.0
      scipy==1.13.1
      transformers==4.44.2
      # metrics
      bert-score==0.3.13
      bertviz==1.4.0
      sacrebleu==2.4.3
      sentencepiece==0.2.0
      seqeval==1.2.2
      torchinfo==1.8.0
  python_llm_store_pip_sh:
    content: |
      #!/bin/sh
      set -x
      rm -rf ./dist/*
      cp ./* ./dist/
      pip download -r ./dist/llm_requirements.txt -d ./dist/pkgs
      # tar -zcf pkgs.tar.gz ./dist/pkgs && rm -rf ./dist/pkgs

# volumes:
#   vol-artifact:

services:
  python_llm_store:
    image: python:3.10.12
    user: *user
    working_dir: "/src"
    command:
      - "/bin/sh"
      - "-c"
      - *python_llm_store_pip_sh
    # command: "./llm_store_pip.sh"
    # configs:
    #   - source: python_llm_store_pip_sh
    #     target: "/src/llm_store_pip.sh"
    #     mode: 0777
    #   - source: python_llm_requirements_txt
    #     target: "/src/llm_requirements.txt"
    volumes:
      - type: bind
        source: *host_share_path
        target: "/src/dist"
        read_only: false
      # - type: volume
      #   source: vol-artifact
      #   target: "/src/dist"
