FROM busybox AS stage-0_download
WORKDIR /downloads
RUN wget https://github.com/kasmtech/KasmVNC/releases/download/v1.3.1/kasmvncserver_focal_1.3.1_amd64.deb


FROM ubuntu:20.04
COPY --from=stage-0_download /downloads /src

WORKDIR /src

RUN apt update
RUN apt install -y sudo fluxbox xterm ./kasmvncserver_$(. /etc/os-release && echo "$VERSION_CODENAME")_1.3.1_amd64.deb

RUN groupadd -g 1234 xuser && \
    useradd -m -u 1234 -g xuser xuser
# RUN adduser --disabled-password --gecos '' xuser
# RUN adduser xuser sudo
RUN adduser xuser ssl-cert

WORKDIR /home/xuser

COPY <<EOF .vnc/xstartup
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
fluxbox
EOF

RUN chmod 777 .vnc/xstartup
RUN chown -R xuser .vnc

USER xuser
