FROM python:3.9

WORKDIR /src

COPY <<EOF /src/requirements.txt
gradio==3.37.0
protobuf==3.20.3
scipy==1.11.1
torch==2.0.1
sentencepiece==0.1.99
transformers==4.31.0
ctransformers==0.2.27
EOF

# RUN apt update
# RUN pip install datasets torchinfo transformers sentencepiece seqeval sacrebleu bert-score bertviz
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt

RUN useradd -m -u 1000 user
USER user

# COPY --link --chown=1000 ./ /src
