FROM ubuntu

WORKDIR /src

RUN wget https://github.com/kasmtech/KasmVNC/releases/download/v1.3.1/kasmvncserver_$(lsb_release -cs)_1.3.1_amd64.deb
RUN apt update
RUN apt install -y fluxbox xterm ./kasmvncserver_$(lsb_release -cs)_1.3.1_amd64.deb

USER user
RUN sudo adduser user ssl-cert
