#### syntax=docker/dockerfile:1
FROM golang:1.22.1 as stage-0_build-bin
WORKDIR /src
COPY <<EOF /src/main_server.go
package main

import (
  "fmt"
  "log"
  "net/http"
)

func main() {
  fileServer := http.FileServer(http.Dir("./"))
  http.Handle("/", fileServer)
  fmt.Printf("Starting server at port 8080\n")
  if err := http.ListenAndServe(":8080", nil); err != nil {
    log.Fatal(err)
  }
}
EOF
RUN go build -ldflags "-linkmode external -extldflags -static" -a -o /bin/go-server ./main_server.go

FROM scratch
COPY --from=stage-0_build-bin /bin/go-server /bin/go-server
CMD ["/bin/go-server"]
