#!/bin/bash
set -ex


sudo apt-get update

# vscode setup: https://code.visualstudio.com/docs/setup/linux
sudo apt-get install -y wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
rm -f packages.microsoft.gpg
# vscode install
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get install -y code # or code-insiders

# pys vscode extensions
code \
  --install-extension ms-python.debugpy \
  --install-extension ms-python.python \
  --install-extension ms-python.vscode-pylance \
  --install-extension ms-toolsai.jupyter \
  --install-extension ms-toolsai.jupyter-keymap \
  --install-extension ms-toolsai.jupyter-renderers \
  --install-extension ms-toolsai.vscode-jupyter-cell-tags \
  --install-extension ms-toolsai.vscode-jupyter-slideshow \
  --force
# pys install
sudo apt-get install -y python3-pip
pip install --break-system-packages ipykernel jupyter matplotlib pandas numpy scipy scikit-learn tensorflow
# jupyter notebook --notebook-dir=/usr/src --ip='*' --port=3100 --no-browser

# clean
sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
