# This is a basic workflow to help you get started with Actions

name: 持续集成CI

# Controls when the action will run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job-Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 显示基本信息 Output basic info
      run: |
        echo "当前Build ID: $GITHUB_RUN_ID"
        echo "当前Build Number: $GITHUB_RUN_NUMBER"
        echo "当前目录为: $GITHUB_WORKSPACE"

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: 代码获取Checkout code
      uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: 运行执行脚本 Run a multi-line script
      run: |
        export ENV_CI_DOCKERIMAGE_THISTAG="$GITHUB_RUN_NUMBER"
        ./run-docker-build-publish.sh
      env:
        ENV_CI_DOCKER_USERNAME: ${{ github.actor }}
        ENV_CI_DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        ENV_CI_DOCKERIMAGE_FEATURENAME: "dev-gate-server"
        ENV_CI_DOCKERIMAGE_REPOURL: "https://github.com/neozxin/ubuntu-init.git"
        ENV_CI_DOCKERIMAGE_REPOYML: "./dev-servers/docker-compose.yml"
